// Package main is the entry point of the Health Pal backend application.
package main

import (
	"context" // Added for graceful shutdown
	"database/sql"
	"fmt"
	"log"
	"net/http" // Added for http.ErrServerClosed
	"os"
	"os/signal" // Added for graceful shutdown
	"syscall" // Added for graceful shutdown
	"time" // Added for database connection timeout

	"github.com/gin-gonic/gin"
	_ "github.com/go-sql-driver/mysql" // MySQL driver
	"github.com/joho/godotenv"

	"health_pal_backend/handlers"   // Import handlers package
	"health_pal_backend/middleware" // Import middleware package
	"health_pal_backend/models"     // Import the models package
	"health_pal_backend/routes"     // Import routes package

	swaggerFiles "github.com/swaggo/files" // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "health_pal_backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Health Pal Backend API
// @version 1.0
// @description This is the API documentation for the Health Pal backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// main function is the entry point of the application.
func main() {
	// Load environment variables from .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	// Database connection string from environment variables
	dbUser := os.Getenv("DB_USER")
	dbPassword := os.Getenv("DB_PASSWORD")
	dbHost := os.Getenv("DB_HOST")
	dbPort := os.Getenv("DB_PORT")
	dbName := os.Getenv("DB_NAME")

	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?parseTime=true", dbUser, dbPassword, dbHost, dbPort, dbName)

	// Open database connection
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("Error opening database connection: %v", err)
	}

	// Set connection pool settings
	db.SetMaxOpenConns(10)  // Max open connections
	db.SetMaxIdleConns(5)   // Max idle connections
	db.SetConnMaxLifetime(5 * time.Minute) // Connection max lifetime

	// Ping the database to verify connection
	err = db.Ping()
	if err != nil {
		log.Fatalf("Error pinging database: %v", err)
	}
	fmt.Println("Successfully connected to MySQL database!")

	// Initialize UserModel
	userModel := &models.UserModel{DB: db}

	// Initialize handlers
	authHandler := &handlers.AuthHandler{UserModel: userModel}
	deletionHandler := &handlers.DeletionHandler{UserModel: userModel}

	router := gin.Default()

	// Load HTML templates
	router.LoadHTMLGlob("templates/*")

	// Setup routes
	routes.SetupRoutes(router, authHandler, deletionHandler)

	// Swagger UI
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server in a goroutine
	go func() {
		if err := router.Run(":8080"); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := db.Close(); err != nil {
		log.Fatal("DB close error:", err)
	}
	log.Println("Server exiting")
}