// Package main is the entry point of the Health Pal backend application.
package main

import (
	"context" // Added for graceful shutdown
	"context" // Added for graceful shutdown
	"fmt"
	"log"
	"net/http" // Added for http.ErrServerClosed
	"os"
	"os/signal" // Added for graceful shutdown
	"syscall" // Added for graceful shutdown
	"time" // Added for database connection timeout

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	"gorm.io/driver/mysql" // GORM MySQL driver
	"gorm.io/gorm"         // GORM

	"health_pal_backend/handlers"   // Import handlers package
	"health_pal_backend/middleware" // Import middleware package
	"health_pal_backend/models"     // Import the models package
	"health_pal_backend/routes"     // Import routes package

	"github.com/swaggo/files"       // swagger embed files
	"github.com/swaggo/gin-swagger" // gin-swagger middleware

	_ "health_pal_backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Health Pal Backend API
// @version 1.0
// @description This is the API documentation for the Health Pal backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// main function is the entry point of the application.
func main() {
	// Load environment variables from .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	// Database connection string from environment variables
	dbUser := os.Getenv("DB_USER")
	dbPassword := os.Getenv("DB_PASSWORD")
	dbHost := os.Getenv("DB_HOST")
	dbPort := os.Getenv("DB_PORT")
	dbName := os.Getenv("DB_NAME")

	dsn := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local", dbUser, dbPassword, dbHost, dbPort, dbName)

	// Initialize GORM DB
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("Error connecting to database: %v", err)
	}
	fmt.Println("Successfully connected to MySQL database with GORM!")

	// Initialize models
	userModel := &models.UserModel{DB: db}
	stepModel := &models.StepModel{DB: db}
	sittingTimeModel := &models.SittingTimeModel{DB: db}
	waterIntakeModel := &models.WaterIntakeModel{DB: db} // Initialize WaterIntakeModel
	foodPhotoModel := &models.FoodPhotoModel{DB: db} // Initialize FoodPhotoModel
	// Retrieve JWT Secret after loading .env
	jwtSecret := []byte(os.Getenv("JWT_SECRET"))

	// Initialize handlers
	authHandler := &handlers.AuthHandler{UserModel: userModel, JWTSecret: jwtSecret}
	deletionHandler := &handlers.DeletionHandler{UserModel: userModel}
	stepHandler := &handlers.StepHandler{StepModel: stepModel}
	sittingTimeHandler := &handlers.SittingTimeHandler{SittingTimeModel: sittingTimeModel}
	waterIntakeHandler := &handlers.WaterIntakeHandler{WaterIntakeModel: waterIntakeModel} // Initialize WaterIntakeHandler
	foodPhotoHandler := &handlers.FoodPhotoHandler{FoodPhotoModel: foodPhotoModel} // Initialize FoodPhotoHandler

	router := gin.Default()

	// Load HTML templates
	router.LoadHTMLGlob("templates/*")

	// Setup routes
	routes.SetupRoutes(router, authHandler, deletionHandler, stepHandler, sittingTimeHandler, waterIntakeHandler, foodPhotoHandler)

	// Swagger UI
	router.GET("/swagger/*any", ginSwagger.WrapHandler(ginSwagger.URL("http://localhost:8080/swagger/doc.json"))) // Use ginSwagger.URL for dynamic host

	// Start the server in a goroutine
	go func() {
		if err := router.Run(":8080"); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	// Graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	// GORM handles connection closing automatically, but you can explicitly close if needed
	// sqlDB, _ := db.DB()
	// if err := sqlDB.Close(); err != nil {
	// 	log.Fatal("DB close error:", err)
	// }
	log.Println("Server exiting")
}